---
title: "About Me"
---

My name is Abbass Sleiman and I am a Lebanese third-year undergraduate student at the University of Toronto pursuing studies in Mathematical Applications in Economics and Finance. I have always been passionate about untangling the world's complexities and understanding its economic and financial dynamics. The practical applications that arise from the many theoretical frameworks developed in economics and finance, along with the many intersections between mathematical concepts and financial practices, have always captivated me. 

However, my passions extend outside just economics and finance. Aside from being a life-long learner, I have always enjoyed teaching others, and as a result I have worked as a Teaching Assistant at the University of Toronto over the course of the current academic year. Outside of academics I greatly enjoy playing music, in particular, I have always been fond of playing the piano and the drums - thus far I have completed Rockschool's Grade 3 examination with Distinction and am hoping to complete Grade 5 in the near future.